version: "3"

services:
  web:
    build: .
    restart: always
    container_name: djangoApp
    expose:
      - "8000"
    env_file: .env
    volumes:
      - ./app:/opt/webapp/
    command: gunicorn app.wsgi:application -w 2 -b :8000
    depends_on:
      - db

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/opt/webapp/
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

  db:
    image: postgres:latest
    restart: always
    container_name: database
    env_file:
      - .env
    expose:
      - 5432