# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=34)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
